"use client";
import React from "react";
import { motion } from "framer-motion";

const DocumentFolder = ({ isOpen, children }) => {
  return (
    <div className="relative w-full max-w-[320px] md:max-w-[400px] aspect-[3/4] mx-auto perspective-[1500px]">
      {/* Back of the Folder */}
      <div 
        className="absolute inset-0 rounded-2xl shadow-2xl overflow-hidden border border-white/5"
        style={{ 
          backgroundColor: "#0d1514", 
          transformStyle: "preserve-3d"
        }}
      >
        <div className="absolute inset-0 bg-gradient-to-br from-[#00d1b2]/10 to-transparent opacity-40" />
      </div>

      {/* The Document (Paper inside) */}
      <motion.div
        initial={false}
        animate={{ 
          y: isOpen ? -30 : 0,
          rotate: isOpen ? -2 : 0,
          scale: isOpen ? 1.05 : 0.95,
          zIndex: 5
        }}
        transition={{ type: "spring", stiffness: 260, damping: 22 }}
        className="absolute inset-4 rounded-xl bg-[#fafafa] shadow-2xl overflow-hidden flex flex-col"
      >
        <div className="absolute top-0 left-0 right-0 h-2 bg-[#00d1b2]/30" />
        <div className="p-6 h-full flex flex-col">
           {children}
        </div>
      </motion.div>

      {/* Front Cover of the Folder */}
      <motion.div
        initial={false}
        animate={{ 
          rotateY: isOpen ? -115 : 0,
          zIndex: isOpen ? 0 : 10
        }}
        transition={{ type: "spring", stiffness: 150, damping: 20 }}
        className="absolute inset-0 rounded-2xl origin-left cursor-pointer preserve-3d overflow-hidden"
        style={{ 
          backgroundColor: "#121b1a",
          backfaceVisibility: "hidden",
          border: "1px solid rgba(0, 209, 178, 0.2)",
          boxShadow: "inset 0px 2px 4px 0px rgba(0, 209, 178, 0.1), 0 20px 50px rgba(0,0,0,0.6)"
        }}
      >
        {/* Background Image generated by AI */}
        <div className="absolute inset-0 z-0 opacity-40">
           <img 
             src="/images/experience_cover.png" 
             alt="Experience Cover" 
             className="w-full h-full object-cover grayscale brightness-50 contrast-125"
           />
           <div className="absolute inset-0 bg-gradient-to-t from-[#121b1a] via-[#121b1a]/40 to-transparent" />
        </div>

        {/* Content on top of image */}
        <div className="relative z-10 p-8 h-full flex flex-col justify-between">
          <div className="flex flex-col gap-2">
            <div className="w-12 h-1 bg-[#00d1b2] rounded-full shadow-[0_0_10px_rgba(0,209,178,0.5)]" />
            <p className="text-[10px] font-mono text-[#00d1b2] font-bold tracking-[0.4em] uppercase">Security Clearance: L3</p>
            <h3 className="text-2xl font-mono font-bold text-white tracking-tight drop-shadow-md">WORK_EXP_V1</h3>
          </div>

          <div className="flex items-center gap-4">
              <div className="w-10 h-10 rounded-xl bg-white/5 backdrop-blur-md flex items-center justify-center border border-white/10 shadow-lg">
                 <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#00d1b2" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"></path>
                 </svg>
              </div>
              <div className="flex flex-col">
                <span className="text-[11px] text-white font-bold uppercase tracking-[0.2em]">Restricted Access</span>
                <span className="text-[9px] text-[#00d1b2]/70 uppercase tracking-widest font-mono">Decryption Key Required</span>
              </div>
          </div>
        </div>

        {/* Subtle glowing texture overlay */}
        <div className="absolute inset-0 bg-gradient-to-tr from-[#00d1b2]/10 via-transparent to-transparent pointer-events-none z-20" />
      </motion.div>
    </div>
  );
};

export default DocumentFolder;
